name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: uraimo/run-on-arch-action@v2
        name: Compile
        id: compile-arm64
        with:
          arch: aarch64
          distro: ubuntu_latest
          base_image: arm64v8/ubuntu:latest
          githubToken: ${{ github.token }}
          run: |
            apt-get update && apt-get install -y \
                build-essential \
                gcc-aarch64-linux-gnu \
                g++-aarch64-linux-gnu \
                zlib1g-dev \
                liblmdb-dev
            cd c++
            rm -rf ReleaseMT/*
            ./configure --build=aarch64-linux
            cd ReleaseMT/build
            make all_r
