name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: uraimo/run-on-arch-action@v2
        name: Build docker image
        id: build-docker
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          run: bin/build.sh
